-- Demo upstream warehouse queried by the demo Metabase instance.
--
-- Fact data is generated by views relative to current_date, using a
-- deterministic hash instead of random(): the same date always yields the same
-- numbers. That keeps "last week" / "last 7 days" dashboards populated no matter
-- when the stack is started, and makes re-downloads of the same window
-- byte-for-byte reproducible (which the idempotency demo relies on).

CREATE SCHEMA sales;
CREATE SCHEMA product;
CREATE SCHEMA finance;

-- Deterministic pseudo-random number in [0, 1) derived from a text key.
CREATE FUNCTION public.demo_rand(key text) RETURNS double precision
    LANGUAGE sql IMMUTABLE AS
$$ SELECT ('x' || substr(md5(key), 1, 8))::bit(32)::bigint::double precision / 4294967296.0 $$;

GRANT EXECUTE ON FUNCTION public.demo_rand(text) TO PUBLIC;

-- ---------------------------------------------------------------------------
-- Sales
-- ---------------------------------------------------------------------------
CREATE TABLE sales.products (
    product_id   integer PRIMARY KEY,
    product_name text          NOT NULL,
    category     text          NOT NULL,
    unit_price   numeric(10,2) NOT NULL
);

-- A few values are deliberately messy (padding, casing) the way real exports are.
INSERT INTO sales.products VALUES
    (1,  'Aurora Desk Lamp',        'Home Office', 49.00),
    (2,  'Nimbus Standing Desk ',   'Home Office', 489.00),
    (3,  'Pulse Wireless Mouse',    'Accessories', 29.50),
    (4,  'Pulse Mechanical Keyboard','Accessories', 119.00),
    (5,  ' Vista 27" Monitor',      'displays',    329.99),
    (6,  'Vista 34" Ultrawide',     'Displays',    599.00),
    (7,  'Echo Noise-Cancel Headset','Audio',      189.00),
    (8,  'Echo Desk Speakers',      'audio ',      99.00),
    (9,  'Orbit USB-C Dock',        'Accessories', 159.00),
    (10, 'Orbit Laptop Stand',      'Home Office', 59.00);

CREATE TABLE sales.regions (region text PRIMARY KEY);
INSERT INTO sales.regions VALUES ('North'), ('South'), ('East'), ('West');

CREATE VIEW sales.daily_product_sales AS
SELECT
    d::date                                                   AS sale_date,
    r.region,
    p.product_name,
    p.category,
    q.orders,
    q.units,
    round(q.units * p.unit_price * (1 - q.discount), 2)       AS revenue
FROM generate_series(current_date - 400, current_date - 1, interval '1 day') AS d
CROSS JOIN sales.regions  AS r
CROSS JOIN sales.products AS p
CROSS JOIN LATERAL (
    SELECT
        o.orders,
        o.orders + floor(demo_rand(k || ':u') * o.orders)::int AS units,
        round((demo_rand(k || ':d') * 0.15)::numeric, 2)       AS discount
    FROM (
        SELECT d::date::text || r.region || p.product_id AS k
    ) AS key
    CROSS JOIN LATERAL (
        SELECT 1 + floor(demo_rand(key.k || ':o') * 12)::int AS orders
    ) AS o
) AS q;

-- ---------------------------------------------------------------------------
-- Product usage (long / "tidy" format: one row per account, day and metric)
-- ---------------------------------------------------------------------------
CREATE TABLE product.accounts (
    account_id   text PRIMARY KEY,
    account_name text NOT NULL,
    plan         text NOT NULL,
    seats        integer NOT NULL
);

INSERT INTO product.accounts VALUES
    ('ACC-1001', 'Acme Logistics',      'Enterprise', 250),
    ('ACC-1002', 'Brightline Health',   'Enterprise', 180),
    ('ACC-1003', 'Cobalt Robotics',     'Growth',      60),
    ('ACC-1004', 'Dunmore & Co',        'Starter',     12),
    ('ACC-1005', 'Evergreen Foods',     'Growth',      45),
    ('ACC-1006', 'Fathom Analytics',    'Enterprise', 320),
    ('ACC-1007', 'Granite Legal',       'Starter',      8),
    ('ACC-1008', 'Harbor Freight Labs', 'Growth',      75),
    ('ACC-1009', 'Iris Media',          'Starter',     15),
    ('ACC-1010', 'Juniper Energy',      'Enterprise', 210);

CREATE VIEW product.usage_metrics_daily AS
SELECT
    d::date        AS usage_date,
    a.account_id,
    a.account_name,
    a.plan,
    m.metric,
    CASE m.metric
        WHEN 'active_users' THEN floor(a.seats * (0.35 + 0.6 * demo_rand(d::date || a.account_id || 'au')))
        WHEN 'sessions'     THEN floor(a.seats * (0.8 + 2.5 * demo_rand(d::date || a.account_id || 'se')))
        WHEN 'api_calls'    THEN floor(a.seats * (40 + 400 * demo_rand(d::date || a.account_id || 'api')))
        WHEN 'storage_gb'   THEN round((a.seats * 0.8 + (current_date - d::date) * -0.01
                                        + 5 * demo_rand(d::date || a.account_id || 'st'))::numeric, 2)
    END::numeric   AS value
FROM generate_series(current_date - 120, current_date - 1, interval '1 day') AS d
CROSS JOIN product.accounts AS a
CROSS JOIN (VALUES ('active_users'), ('sessions'), ('api_calls'), ('storage_gb')) AS m(metric);

-- ---------------------------------------------------------------------------
-- Finance (static archive; details is nested JSON as produced by the ERP)
-- ---------------------------------------------------------------------------
CREATE TABLE finance.budget_lines (
    line_id        text PRIMARY KEY,
    fiscal_quarter text          NOT NULL,
    period_month   date          NOT NULL,
    department     text          NOT NULL,
    cost_center    text          NOT NULL,
    category       text          NOT NULL,
    budget         numeric(14,2) NOT NULL,
    actual         numeric(14,2),
    details        jsonb         NOT NULL
);

INSERT INTO finance.budget_lines
SELECT
    format('BL-%s-%s-%s', dept.code, to_char(m, 'YYYYMM'), cat.code)                        AS line_id,
    'FY2025-Q4'                                                                               AS fiscal_quarter,
    m::date                                                                                   AS period_month,
    dept.name                                                                                 AS department,
    format('CC-%s-%s', dept.code, cat.code)                                                   AS cost_center,
    cat.name                                                                                  AS category,
    round((cat.base * dept.scale)::numeric, 2)                                                AS budget,
    -- December actuals for one department are not yet booked (NULL) - realistic gap.
    CASE WHEN dept.code = 'MKT' AND extract(month FROM m) = 12 THEN NULL
         ELSE round((cat.base * dept.scale * (0.82 + 0.36 * demo_rand(dept.code || cat.code || m::date)))::numeric, 2)
    END                                                                                       AS actual,
    jsonb_build_object(
        'owner',    jsonb_build_object('name', dept.owner, 'email', lower(replace(dept.owner, ' ', '.')) || '@example.com'),
        'approval', jsonb_build_object(
                        'status',      CASE WHEN extract(month FROM m) = 12 AND dept.code IN ('MKT', 'ENG') THEN 'pending' ELSE 'approved' END,
                        'approved_by', CASE WHEN extract(month FROM m) = 12 AND dept.code IN ('MKT', 'ENG') THEN NULL ELSE 'CFO Office' END,
                        'approved_at', CASE WHEN extract(month FROM m) = 12 AND dept.code IN ('MKT', 'ENG') THEN NULL
                                            ELSE to_char(m - interval '10 days', 'YYYY-MM-DD"T"09:30:00"Z"') END),
        'forecast', jsonb_build_object('next_quarter', round((cat.base * dept.scale * 1.05)::numeric, 2), 'currency', 'USD')
    )                                                                                         AS details
FROM generate_series('2025-10-01'::date, '2025-12-01'::date, interval '1 month') AS m
CROSS JOIN (VALUES
    ('ENG', 'Engineering', 3.0, 'Priya Raman'),
    ('MKT', 'Marketing',   1.6, 'Daniel Okafor'),
    ('SAL', 'Sales',       2.2, 'Mei Tanaka'),
    ('OPS', 'Operations',  1.2, 'Lucas Moreau'),
    ('FIN', 'Finance',     0.7, 'Sara Lindqvist'),
    ('PPL', 'People',      0.8, 'Omar Haddad')
) AS dept(code, name, scale, owner)
CROSS JOIN (VALUES
    ('PAY', 'Payroll',  120000),
    ('SW',  'Software',  18000),
    ('TRV', 'Travel',     9000)
) AS cat(code, name, base);
